/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as MeusPedidosRouteImport } from './routes/meus-pedidos'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as PainelVendedorRouteImport } from './routes/painel-vendedor'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AdminAvaliacoesRouteImport } from './routes/admin_.avaliacoes'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin_.configuracoes'
import { Route as AdminSolicitacoesRouteImport } from './routes/admin_.solicitacoes'
import { Route as BoxSlugRouteImport } from './routes/box.$slug'
import { Route as PainelVendedorCertificadoRouteImport } from './routes/painel-vendedor_.certificado'
import { Route as PainelVendedorEstoqueRouteImport } from './routes/painel-vendedor_.estoque'
import { Route as PainelVendedorNotasRouteImport } from './routes/painel-vendedor_.notas'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusPedidosRoute = MeusPedidosRouteImport.update({
  id: '/meus-pedidos',
  path: '/meus-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelVendedorRoute = PainelVendedorRouteImport.update({
  id: '/painel-vendedor',
  path: '/painel-vendedor',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAvaliacoesRoute = AdminAvaliacoesRouteImport.update({
  id: '/admin_/avaliacoes',
  path: '/admin/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/admin_/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSolicitacoesRoute = AdminSolicitacoesRouteImport.update({
  id: '/admin_/solicitacoes',
  path: '/admin/solicitacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxSlugRoute = BoxSlugRouteImport.update({
  id: '/box/$slug',
  path: '/box/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelVendedorCertificadoRoute =
  PainelVendedorCertificadoRouteImport.update({
    id: '/painel-vendedor_/certificado',
    path: '/painel-vendedor/certificado',
    getParentRoute: () => rootRouteImport,
  } as any)
const PainelVendedorEstoqueRoute = PainelVendedorEstoqueRouteImport.update({
  id: '/painel-vendedor_/estoque',
  path: '/painel-vendedor/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelVendedorNotasRoute = PainelVendedorNotasRouteImport.update({
  id: '/painel-vendedor_/notas',
  path: '/painel-vendedor/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/carrinho': typeof CarrinhoRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/notificacoes': typeof NotificacoesRoute
  '/painel': typeof PainelRoute
  '/painel-vendedor': typeof PainelVendedorRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/box/$slug': typeof BoxSlugRoute
  '/painel-vendedor/certificado': typeof PainelVendedorCertificadoRoute
  '/painel-vendedor/estoque': typeof PainelVendedorEstoqueRoute
  '/painel-vendedor/notas': typeof PainelVendedorNotasRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/carrinho': typeof CarrinhoRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/notificacoes': typeof NotificacoesRoute
  '/painel': typeof PainelRoute
  '/painel-vendedor': typeof PainelVendedorRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/box/$slug': typeof BoxSlugRoute
  '/painel-vendedor/certificado': typeof PainelVendedorCertificadoRoute
  '/painel-vendedor/estoque': typeof PainelVendedorEstoqueRoute
  '/painel-vendedor/notas': typeof PainelVendedorNotasRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/carrinho': typeof CarrinhoRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/notificacoes': typeof NotificacoesRoute
  '/painel': typeof PainelRoute
  '/painel-vendedor': typeof PainelVendedorRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin_/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin_/configuracoes': typeof AdminConfiguracoesRoute
  '/admin_/solicitacoes': typeof AdminSolicitacoesRoute
  '/box/$slug': typeof BoxSlugRoute
  '/painel-vendedor_/certificado': typeof PainelVendedorCertificadoRoute
  '/painel-vendedor_/estoque': typeof PainelVendedorEstoqueRoute
  '/painel-vendedor_/notas': typeof PainelVendedorNotasRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/buscar'
    | '/carrinho'
    | '/meus-pedidos'
    | '/notificacoes'
    | '/painel'
    | '/painel-vendedor'
    | '/perfil'
    | '/privacidade'
    | '/termos'
    | '/admin/avaliacoes'
    | '/admin/configuracoes'
    | '/admin/solicitacoes'
    | '/box/$slug'
    | '/painel-vendedor/certificado'
    | '/painel-vendedor/estoque'
    | '/painel-vendedor/notas'
    | '/produto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/buscar'
    | '/carrinho'
    | '/meus-pedidos'
    | '/notificacoes'
    | '/painel'
    | '/painel-vendedor'
    | '/perfil'
    | '/privacidade'
    | '/termos'
    | '/admin/avaliacoes'
    | '/admin/configuracoes'
    | '/admin/solicitacoes'
    | '/box/$slug'
    | '/painel-vendedor/certificado'
    | '/painel-vendedor/estoque'
    | '/painel-vendedor/notas'
    | '/produto/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/buscar'
    | '/carrinho'
    | '/meus-pedidos'
    | '/notificacoes'
    | '/painel'
    | '/painel-vendedor'
    | '/perfil'
    | '/privacidade'
    | '/termos'
    | '/admin_/avaliacoes'
    | '/admin_/configuracoes'
    | '/admin_/solicitacoes'
    | '/box/$slug'
    | '/painel-vendedor_/certificado'
    | '/painel-vendedor_/estoque'
    | '/painel-vendedor_/notas'
    | '/produto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BuscarRoute: typeof BuscarRoute
  CarrinhoRoute: typeof CarrinhoRoute
  MeusPedidosRoute: typeof MeusPedidosRoute
  NotificacoesRoute: typeof NotificacoesRoute
  PainelRoute: typeof PainelRoute
  PainelVendedorRoute: typeof PainelVendedorRoute
  PerfilRoute: typeof PerfilRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  AdminAvaliacoesRoute: typeof AdminAvaliacoesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminSolicitacoesRoute: typeof AdminSolicitacoesRoute
  BoxSlugRoute: typeof BoxSlugRoute
  PainelVendedorCertificadoRoute: typeof PainelVendedorCertificadoRoute
  PainelVendedorEstoqueRoute: typeof PainelVendedorEstoqueRoute
  PainelVendedorNotasRoute: typeof PainelVendedorNotasRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-pedidos': {
      id: '/meus-pedidos'
      path: '/meus-pedidos'
      fullPath: '/meus-pedidos'
      preLoaderRoute: typeof MeusPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-vendedor': {
      id: '/painel-vendedor'
      path: '/painel-vendedor'
      fullPath: '/painel-vendedor'
      preLoaderRoute: typeof PainelVendedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/avaliacoes': {
      id: '/admin_/avaliacoes'
      path: '/admin/avaliacoes'
      fullPath: '/admin/avaliacoes'
      preLoaderRoute: typeof AdminAvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/configuracoes': {
      id: '/admin_/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/solicitacoes': {
      id: '/admin_/solicitacoes'
      path: '/admin/solicitacoes'
      fullPath: '/admin/solicitacoes'
      preLoaderRoute: typeof AdminSolicitacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box/$slug': {
      id: '/box/$slug'
      path: '/box/$slug'
      fullPath: '/box/$slug'
      preLoaderRoute: typeof BoxSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-vendedor_/certificado': {
      id: '/painel-vendedor_/certificado'
      path: '/painel-vendedor/certificado'
      fullPath: '/painel-vendedor/certificado'
      preLoaderRoute: typeof PainelVendedorCertificadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-vendedor_/estoque': {
      id: '/painel-vendedor_/estoque'
      path: '/painel-vendedor/estoque'
      fullPath: '/painel-vendedor/estoque'
      preLoaderRoute: typeof PainelVendedorEstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-vendedor_/notas': {
      id: '/painel-vendedor_/notas'
      path: '/painel-vendedor/notas'
      fullPath: '/painel-vendedor/notas'
      preLoaderRoute: typeof PainelVendedorNotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BuscarRoute: BuscarRoute,
  CarrinhoRoute: CarrinhoRoute,
  MeusPedidosRoute: MeusPedidosRoute,
  NotificacoesRoute: NotificacoesRoute,
  PainelRoute: PainelRoute,
  PainelVendedorRoute: PainelVendedorRoute,
  PerfilRoute: PerfilRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  AdminAvaliacoesRoute: AdminAvaliacoesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminSolicitacoesRoute: AdminSolicitacoesRoute,
  BoxSlugRoute: BoxSlugRoute,
  PainelVendedorCertificadoRoute: PainelVendedorCertificadoRoute,
  PainelVendedorEstoqueRoute: PainelVendedorEstoqueRoute,
  PainelVendedorNotasRoute: PainelVendedorNotasRoute,
  ProdutoIdRoute: ProdutoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
